#!/usr/bin/env bash

SUBCOMMAND_DESC="Descarregar html da camera de deputados"
SUBCOMMAND_HELP=$(cat <<EOH
remuneracoes_deputados        Remunerações de todos os deputados
remuneracoes_fucionario       Remunerações de um funcionario especifico
nomes_deputados               Nomes de deputados
deputado                      Informação de um deputado
lista_deputados               Lista de todos os deputados
legislatura                   Informações de uma legislatura
EOH
)

case ${1} in
  remuneracoes_deputados)
    ano=${2}
    mes=${3}

    if [[ -z ${ano} ]]; then
      in_red ">"; echo "ano não especificado"
      bold "Uso:"; echo "     ${MAIN_COMMAND} ${SUBCOMMAND} ${1} <ano> [mes]"
      bold "Exemplo:"; echo " ${MAIN_COMMAND} ${SUBCOMMAND} ${1} 2017"
      bold "Exemplo:"; echo " ${MAIN_COMMAND} ${SUBCOMMAND} ${1} 2017 5"
      bold "$(smul Parametros)"; echo
      bold "ano:"; echo "     ano no formato YYYY"
      bold "mes:"; echo "     mes no formato MM (opcional)"
      exit
    fi

    descarregar/remuneracoes_deputados ${ano} ${mes}
  ;;

  remuneracoes_funcionario)
    ano=${2}
    mes=${3}
    nome="${@:4}"

    if [[ -z ${ano} ]] || [[ -z ${mes} ]] || [[ -z ${nome} ]]; then
      in_red ">"; echo "ano, mes ou nome não especificados"
      bold "Uso:"; echo "     ${MAIN_COMMAND} ${SUBCOMMAND} ${1} <ano> <mes> <nome>"
      bold "Exemplo:"; echo " ${MAIN_COMMAND} ${SUBCOMMAND} ${1} 2000 12 \"ZE CARIOCA\""
      bold "$(smul Parametros)"; echo
      bold "ano:"; echo "     ano no formato YYYY"
      bold "mes:"; echo "     mes no formato MM"
      bold "nome:"; echo "    nome completo do funcionario, cercado de aspas duplas."
      exit
    fi

    descarregar/remuneracoes_funcionario ${ano} ${mes} "${nome}"
  ;;

  nomes_deputados)
    ano=${2}

    if [[ -z ${ano} ]]; then
      in_red ">"; echo "ano não especificado"
      bold "Uso:"; echo "     ${MAIN_COMMAND} ${SUBCOMMAND} ${1} <ano>"
      bold "Exemplo:"; echo " ${MAIN_COMMAND} ${SUBCOMMAND} ${1} 2017"
      bold "$(smul Parametros)"; echo
      bold "ano:"; echo "     ano no formato YYYY"
      exit
    fi

    descarregar/nomes_deputados ${ano}
  ;;

  deputado)
    id=${2}

    if [[ -z ${id} ]]; then
      in_red ">"; echo "id não especificado"
      bold "Uso:"; echo "     ${MAIN_COMMAND} ${SUBCOMMAND} ${1} <id>"
      bold "Exemplo:"; echo " ${MAIN_COMMAND} ${SUBCOMMAND} ${1} 123456"
      bold "$(smul Parametros)"; echo
      bold "id:"; echo "     identificador numérico do deputado"
      exit
    fi

    descarregar/deputado ${id}
  ;;

  lista_deputados)
    ano=${2}

    if [[ -z ${ano} ]]; then
      in_red ">"; echo "ano não especificado"
      bold "Uso:"; echo "     ${MAIN_COMMAND} ${SUBCOMMAND} ${1} <ano>"
      bold "Exemplo:"; echo " ${MAIN_COMMAND} ${SUBCOMMAND} ${1} 2017"
      bold "$(smul Parametros)"; echo
      bold "ano:"; echo "     ano no formato YYYY"
      exit
    fi

    descarregar/lista_deputados ${ano}
  ;;

  legislatura)
    ano=${2}

    if [[ -z ${ano} ]]; then
      in_red ">"; echo "ano não especificado"
      bold "Uso:"; echo "     ${MAIN_COMMAND} ${SUBCOMMAND} ${1} <ano>"
      bold "Exemplo:"; echo " ${MAIN_COMMAND} ${SUBCOMMAND} ${1} 2017"
      bold "$(smul Parametros)"; echo
      bold "ano:"; echo "     ano no formato YYYY"
      exit
    fi

    descarregar/legislatura ${ano}
  ;;

  *)
    if [ ! -z ${1} ]
    then
      in_red "'${1}' not found"
      _help
    fi
esac
