#!/usr/bin/env bash

SUBCOMMAND_DESC="Descarregar html da camera de deputados"
SUBCOMMAND_HELP=$(cat <<EOH
remuneracoes_deputados        Descarregar remunerações deputados
EOH
)

case ${1} in
  remuneracoes_deputados)
    ano="${2}"
    mes="${3}"

    if [[ -z ${ano} ]]; then
      in_red ">"; echo "ano não especificado"
      bold "Uso:"; echo "     ${MAIN_COMMAND} ${SUBCOMMAND} ${1} <ano> [mes]"
      bold "Exemplo:"; echo " ${MAIN_COMMAND} ${SUBCOMMAND} ${1} 2017"
      bold "Exemplo:"; echo " ${MAIN_COMMAND} ${SUBCOMMAND} ${1} 2017 5"
      bold "$(smul Parametros)"; echo
      bold "ano:"; echo "     ano no formato YYYY"
      bold "mes:"; echo "     mes no formato MM (opcional)"
      exit
    fi

    descarregar/remuneracoes_deputados ${ano} ${mes}
  ;;
esac
