#!/usr/bin/env bash

source camara.d/utils

ano=${1}

log "${0}: parametros [ano=${ano}]"

path=/dados/deputados/nomes
file=${ano}.txt
file_path=${path}/${file}

log "${0}: detectar se aquivo existe file_path=${file_path}]"
if [ ! -f  ${file_path} ]; then
  log "${0}: file_path não foi encontrado"
  log "${0}: descarregando nomes deputados para o ano ${ano}"
  descarregar/nomes_deputados ${ano}
else
  log "${0}: file_path foi encontrado"
fi

log "${0}: retornando nomes de deputados para o ano ${ano}"
cat ${file_path}
