#!/usr/bin/env bash

source utils/terminal

set -e

ano=${1}

log "${0}: parametros [ano=${ano}]"

descarregar/nomes_deputados ${ano}

path=/dados/nomes_deputados
file=${ano}.txt
file_path=${path}/${file}

log "${0}: retornando nomes de deputados para o ano ${ano}"
cat ${file_path} | sort
