#!/usr/bin/env bash

source utils/terminal

set -e

ano=${1}
log "${0}: parametros [ano=${ano}]"

file_path=/dados/nomes_deputados/${ano}.txt
if [ -f  ${file_path} ]; then
  log "${0}: ${file_path} foi encontrado, não sera descarregado"
  exit
else
  log "${0}: ${file_path} não foi encontrado"
fi

log "${0}: coletando nomes de deputados do ano ${ano} da lista de deputados"
obter/lista_deputados_ids ${ano} | parallel -j ${JOBS} descarregar/deputado_nome_civil {} ${ano}
